/**
 * Candid — Proofly's own encoder and decoder.
 *
 * Candid is the Thebes Protocol's wire format: the boundary hands a contract a
 * byte string and the contract's Rust CDK decodes it as Candid. This module is
 * that format, implemented here, so the app carries no external codec.
 *
 * ── Why this file exists rather than a dependency ───────────────────────────
 *
 * Proofly used a third-party Candid package until this file replaced it. Two
 * reasons it had to go:
 *
 *   1. Proofly is a Thebes application. It depends on no other chain's
 *      ecosystem packages.
 *   2. That package is deprecated by its own maintainers — installing it
 *      printed a notice pointing at a successor. A deprecated dependency, for a
 *      format we use one narrow slice of, is not worth carrying.
 *
 * ── What it covers, and what it deliberately does not ───────────────────────
 *
 * This implements exactly the slice `backend/backend.did` uses:
 *
 *      text · nat8 · nat64 · null · vec · record · variant
 *
 * That is a deliberate floor, not an unfinished one. `opt`, `int*`, `float*`,
 * `principal`, `func`, `service`, `reserved`, `empty` and recursive types are
 * NOT implemented, and every one of them **throws on sight** rather than
 * guessing — a silently wrong decode of an employment record is worse than a
 * loud failure. If the contract's interface ever grows one of them, this file
 * fails immediately and visibly, which is the intended behaviour.
 *
 * ── How it is known to be correct ───────────────────────────────────────────
 *
 * `scripts/candid-fixtures.json` holds golden byte vectors generated by the
 * reference implementation for every method in the interface, in both variant
 * arms, including an empty vector, an empty string and non-ASCII text.
 * `npm run check:codec` asserts this codec reproduces those bytes exactly and
 * decodes them back to the same values. Those vectors are ground truth from an
 * implementation this one never shared code with.
 *
 * The wire format is Candid, as Thebes speaks it. Every type opcode this file
 * handles is named and numbered immediately below.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Wire primitives
// ─────────────────────────────────────────────────────────────────────────────

/** Type opcodes, as they appear SLEB128-encoded on the wire. */
const OP_NULL = -1;
const OP_NAT8 = -5;
const OP_NAT64 = -8;
const OP_TEXT = -15;
const OP_OPT = -18;
const OP_VEC = -19;
const OP_RECORD = -20;
const OP_VARIANT = -21;

const MAGIC = [0x44, 0x49, 0x44, 0x4c]; // "DIDL"

const utf8Encode = new TextEncoder();
/** `fatal` matters: a malformed reply must fail, not yield replacement chars. */
const utf8Decode = new TextDecoder('utf-8', { fatal: true });

function leb128(value: number | bigint, out: number[]): void {
    let v = BigInt(value);
    if (v < 0n) throw new RangeError('leb128 is unsigned');
    do {
        let byte = Number(v & 0x7fn);
        v >>= 7n;
        if (v > 0n) byte |= 0x80;
        out.push(byte);
    } while (v > 0n);
}

function sleb128(value: number | bigint, out: number[]): void {
    let v = BigInt(value);
    for (;;) {
        const byte = Number(v & 0x7fn);
        v >>= 7n; // BigInt shift is arithmetic, so this terminates at -1 for negatives
        const signSet = (byte & 0x40) !== 0;
        if ((v === 0n && !signSet) || (v === -1n && signSet)) {
            out.push(byte);
            return;
        }
        out.push(byte | 0x80);
    }
}

/**
 * A Candid field label's numeric id: the 32-bit hash of its name.
 *
 * Field *names* never appear on the wire — only these hashes — which is why
 * decoding needs the expected type to recover them.
 */
function fieldHash(name: string): number {
    let h = 0n;
    for (const byte of utf8Encode.encode(name)) {
        h = (h * 223n + BigInt(byte)) & 0xffffffffn;
    }
    return Number(h);
}

class Reader {
    private readonly buf: Uint8Array;
    private pos: number;

    constructor(buf: Uint8Array) {
        this.buf = buf;
        this.pos = 0;
    }

    private need(n: number): void {
        if (this.pos + n > this.buf.length) {
            throw new Error(
                `truncated Candid: wanted ${n} byte(s) at offset ${this.pos}, ` +
                    `only ${this.buf.length - this.pos} remain`
            );
        }
    }

    byte(): number {
        this.need(1);
        return this.buf[this.pos++];
    }

    take(n: number): Uint8Array {
        this.need(n);
        const slice = this.buf.subarray(this.pos, this.pos + n);
        this.pos += n;
        return slice;
    }

    leb(): bigint {
        let result = 0n;
        let shift = 0n;
        for (;;) {
            const byte = this.byte();
            result |= BigInt(byte & 0x7f) << shift;
            if ((byte & 0x80) === 0) return result;
            shift += 7n;
            if (shift > 128n) throw new Error('leb128 value is implausibly long');
        }
    }

    sleb(): bigint {
        let result = 0n;
        let shift = 0n;
        for (;;) {
            const byte = this.byte();
            result |= BigInt(byte & 0x7f) << shift;
            shift += 7n;
            if ((byte & 0x80) === 0) {
                if ((byte & 0x40) !== 0) result -= 1n << shift; // sign-extend
                return result;
            }
            if (shift > 128n) throw new Error('sleb128 value is implausibly long');
        }
    }

    /** Length as a JS number, rejecting anything that cannot be one. */
    count(): number {
        const n = this.leb();
        if (n > 0x7fffffffn) throw new Error(`implausible Candid length: ${n}`);
        return Number(n);
    }

    /**
     * A field label id.
     *
     * Read separately from `count()` because it is a full unsigned 32-bit
     * hash: `employee_name` hashes to 2,643,220,632, which is larger than any
     * length this codec will accept. Reading one as a length rejects every
     * record with a high-hashing field name.
     */
    labelId(): number {
        const n = this.leb();
        if (n > 0xffffffffn) throw new Error(`field label id out of range: ${n}`);
        return Number(n);
    }

    get exhausted(): boolean {
        return this.pos >= this.buf.length;
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// The wire's own view of a type
//
// Parsed from the message's type table. A reference is negative for a
// primitive (it *is* the opcode) and non-negative for an index into the table.
// ─────────────────────────────────────────────────────────────────────────────

type WireType =
    | { k: 'prim'; code: number }
    | { k: 'vec'; elem: number }
    | { k: 'opt'; elem: number }
    | { k: 'record'; fields: Array<[number, number]> }
    | { k: 'variant'; fields: Array<[number, number]> };

/** Resolves a wire type reference against the message's type table. */
type Deref = (ref: number) => WireType;

function parseTableEntry(r: Reader): WireType {
    const op = Number(r.sleb());
    switch (op) {
        case OP_VEC:
            return { k: 'vec', elem: Number(r.sleb()) };
        case OP_OPT:
            return { k: 'opt', elem: Number(r.sleb()) };
        case OP_RECORD:
        case OP_VARIANT: {
            const n = r.count();
            const fields: Array<[number, number]> = [];
            for (let i = 0; i < n; i++) {
                fields.push([r.labelId(), Number(r.sleb())]);
            }
            return { k: op === OP_RECORD ? 'record' : 'variant', fields };
        }
        default:
            throw new Error(
                `unsupported Candid type opcode ${op} in the type table. ` +
                    `This codec implements text/nat8/nat64/null/vec/record/variant only.`
            );
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The type table under construction.
 *
 * Composite types are appended children-first and deduplicated by their
 * structural name, which is what makes the output byte-for-byte identical to
 * the reference encoder's.
 */
class TypeTable {
    private readonly index = new Map<string, number>();
    private readonly entries: number[][] = [];

    has(name: string): boolean {
        return this.index.has(name);
    }

    add(name: string, bytes: number[]): void {
        this.index.set(name, this.entries.length);
        this.entries.push(bytes);
    }

    indexOf(name: string): number {
        const i = this.index.get(name);
        if (i === undefined) throw new Error(`type ${name} was never added to the table`);
        return i;
    }

    encode(out: number[]): void {
        leb128(this.entries.length, out);
        for (const entry of this.entries) out.push(...entry);
    }
}

export abstract class CandidType<T = unknown> {
    /** Structural identity, used to deduplicate table entries. */
    abstract readonly name: string;

    /** Primitives return their opcode; composites their table index. */
    abstract ref(table: TypeTable): number;

    /** Registers this type (children first) in the table. Primitives: no-op. */
    build(_table: TypeTable): void {}

    abstract encodeValue(value: T, out: number[]): void;

    abstract decodeValue(r: Reader, wire: WireType, deref: Deref): T;

    protected expectPrim(wire: WireType, code: number): void {
        if (wire.k !== 'prim' || wire.code !== code) {
            throw new Error(`expected ${this.name} on the wire, got ${describe(wire)}`);
        }
    }
}

function describe(w: WireType): string {
    switch (w.k) {
        case 'prim':
            return `primitive ${w.code}`;
        default:
            return w.k;
    }
}

abstract class PrimType<T> extends CandidType<T> {
    protected abstract readonly opcode: number;
    ref(): number {
        return this.opcode;
    }
}

class TextType extends PrimType<string> {
    readonly name = 'text';
    protected readonly opcode = OP_TEXT;

    encodeValue(value: string, out: number[]): void {
        if (typeof value !== 'string') throw new TypeError(`text expects a string, got ${typeof value}`);
        const bytes = utf8Encode.encode(value);
        leb128(bytes.length, out);
        out.push(...bytes);
    }

    decodeValue(r: Reader, wire: WireType): string {
        this.expectPrim(wire, OP_TEXT);
        return utf8Decode.decode(r.take(r.count()));
    }
}

class Nat8Type extends PrimType<number> {
    readonly name = 'nat8';
    protected readonly opcode = OP_NAT8;

    encodeValue(value: number, out: number[]): void {
        if (!Number.isInteger(value) || value < 0 || value > 255) {
            throw new RangeError(`nat8 out of range: ${value}`);
        }
        out.push(value);
    }

    decodeValue(r: Reader, wire: WireType): number {
        this.expectPrim(wire, OP_NAT8);
        return r.byte();
    }
}

/** Decoded as a bigint: a nat64 does not fit a JS number. */
class Nat64Type extends PrimType<bigint> {
    readonly name = 'nat64';
    protected readonly opcode = OP_NAT64;

    encodeValue(value: bigint | number, out: number[]): void {
        let v = BigInt(value);
        if (v < 0n || v > 0xffffffffffffffffn) throw new RangeError(`nat64 out of range: ${value}`);
        for (let i = 0; i < 8; i++) {
            out.push(Number(v & 0xffn));
            v >>= 8n;
        }
    }

    decodeValue(r: Reader, wire: WireType): bigint {
        this.expectPrim(wire, OP_NAT64);
        const bytes = r.take(8);
        let v = 0n;
        for (let i = 7; i >= 0; i--) v = (v << 8n) | BigInt(bytes[i]);
        return v;
    }
}

class NullType extends PrimType<null> {
    readonly name = 'null';
    protected readonly opcode = OP_NULL;

    encodeValue(): void {
        /* the null value occupies no bytes */
    }

    decodeValue(_r: Reader, wire: WireType): null {
        this.expectPrim(wire, OP_NULL);
        return null;
    }
}

class VecType<T> extends CandidType<T[] | Uint8Array> {
    readonly name: string;
    /** `vec nat8` is Candid's `blob`; the app wants it back as a Uint8Array. */
    private readonly isBlob: boolean;
    private readonly elem: CandidType<T>;

    constructor(elem: CandidType<T>) {
        super();
        this.elem = elem;
        this.name = `vec ${elem.name}`;
        this.isBlob = elem instanceof Nat8Type;
    }

    ref(table: TypeTable): number {
        return table.indexOf(this.name);
    }

    build(table: TypeTable): void {
        if (table.has(this.name)) return;
        this.elem.build(table);
        const bytes: number[] = [];
        sleb128(OP_VEC, bytes);
        sleb128(this.elem.ref(table), bytes);
        table.add(this.name, bytes);
    }

    encodeValue(value: T[] | Uint8Array, out: number[]): void {
        if (this.isBlob && value instanceof Uint8Array) {
            leb128(value.length, out);
            out.push(...value);
            return;
        }
        if (!Array.isArray(value)) {
            throw new TypeError(`${this.name} expects an array, got ${typeof value}`);
        }
        leb128(value.length, out);
        for (const item of value) this.elem.encodeValue(item, out);
    }

    decodeValue(r: Reader, wire: WireType, deref: Deref): T[] | Uint8Array {
        if (wire.k !== 'vec') throw new Error(`expected ${this.name}, got ${describe(wire)}`);
        const elemWire = deref(wire.elem);
        const n = r.count();
        if (this.isBlob) {
            // Not r.take(n): the elements are still decoded one at a time so a
            // wire type that is not nat8 is caught rather than read as bytes.
            const bytes = new Uint8Array(n);
            for (let i = 0; i < n; i++) {
                bytes[i] = this.elem.decodeValue(r, elemWire, deref) as unknown as number;
            }
            return bytes;
        }
        const items: T[] = [];
        for (let i = 0; i < n; i++) items.push(this.elem.decodeValue(r, elemWire, deref));
        return items;
    }
}

/** Field entries, sorted by hash — the order Candid puts them in on the wire. */
function sortedFields(
    fields: Record<string, CandidType<any>>
): Array<[string, number, CandidType<any>]> {
    const entries = Object.entries(fields).map(
        ([label, type]) => [label, fieldHash(label), type] as [string, number, CandidType<any>]
    );
    entries.sort((a, b) => a[1] - b[1]);
    for (let i = 1; i < entries.length; i++) {
        if (entries[i][1] === entries[i - 1][1]) {
            throw new Error(
                `Candid label hash collision between "${entries[i - 1][0]}" and "${entries[i][0]}"`
            );
        }
    }
    return entries;
}

class RecordType extends CandidType<Record<string, any>> {
    readonly name: string;
    private readonly fields: Array<[string, number, CandidType<any>]>;

    constructor(fields: Record<string, CandidType<any>>) {
        super();
        this.fields = sortedFields(fields);
        this.name = `record {${this.fields.map(([l, , t]) => `${l}:${t.name}`).join(';')}}`;
    }

    ref(table: TypeTable): number {
        return table.indexOf(this.name);
    }

    build(table: TypeTable): void {
        if (table.has(this.name)) return;
        for (const [, , type] of this.fields) type.build(table);
        const bytes: number[] = [];
        sleb128(OP_RECORD, bytes);
        leb128(this.fields.length, bytes);
        for (const [, hash, type] of this.fields) {
            leb128(hash, bytes);
            sleb128(type.ref(table), bytes);
        }
        table.add(this.name, bytes);
    }

    encodeValue(value: Record<string, any>, out: number[]): void {
        if (value === null || typeof value !== 'object') {
            throw new TypeError(`${this.name} expects an object`);
        }
        for (const [label, , type] of this.fields) {
            if (!(label in value)) throw new TypeError(`record is missing field "${label}"`);
            type.encodeValue(value[label], out);
        }
    }

    decodeValue(r: Reader, wire: WireType, deref: Deref): Record<string, any> {
        if (wire.k !== 'record') throw new Error(`expected ${this.name}, got ${describe(wire)}`);
        if (wire.fields.length !== this.fields.length) {
            throw new Error(
                `record arity mismatch: wire has ${wire.fields.length} field(s), ` +
                    `${this.name} expects ${this.fields.length}`
            );
        }
        const result: Record<string, any> = {};
        // Both sides are hash-sorted, so they line up index for index.
        for (let i = 0; i < wire.fields.length; i++) {
            const [wireHash, wireRef] = wire.fields[i];
            const [label, hash, type] = this.fields[i];
            if (wireHash !== hash) {
                throw new Error(`record field mismatch: wire hash ${wireHash}, expected ${hash} ("${label}")`);
            }
            result[label] = type.decodeValue(r, deref(wireRef), deref);
        }
        return result;
    }
}

class VariantType extends CandidType<Record<string, any>> {
    readonly name: string;
    private readonly fields: Array<[string, number, CandidType<any>]>;

    constructor(fields: Record<string, CandidType<any>>) {
        super();
        this.fields = sortedFields(fields);
        this.name = `variant {${this.fields.map(([l, , t]) => `${l}:${t.name}`).join(';')}}`;
    }

    ref(table: TypeTable): number {
        return table.indexOf(this.name);
    }

    build(table: TypeTable): void {
        if (table.has(this.name)) return;
        for (const [, , type] of this.fields) type.build(table);
        const bytes: number[] = [];
        sleb128(OP_VARIANT, bytes);
        leb128(this.fields.length, bytes);
        for (const [, hash, type] of this.fields) {
            leb128(hash, bytes);
            sleb128(type.ref(table), bytes);
        }
        table.add(this.name, bytes);
    }

    encodeValue(value: Record<string, any>, out: number[]): void {
        if (value === null || typeof value !== 'object') {
            throw new TypeError(`${this.name} expects an object`);
        }
        const present = Object.keys(value);
        if (present.length !== 1) {
            throw new TypeError(`a variant takes exactly one arm, got ${present.length}`);
        }
        const index = this.fields.findIndex(([label]) => label === present[0]);
        if (index < 0) throw new TypeError(`"${present[0]}" is not an arm of ${this.name}`);
        leb128(index, out);
        this.fields[index][2].encodeValue(value[present[0]], out);
    }

    decodeValue(r: Reader, wire: WireType, deref: Deref): Record<string, any> {
        if (wire.k !== 'variant') throw new Error(`expected ${this.name}, got ${describe(wire)}`);
        const index = r.count();
        if (index >= wire.fields.length) {
            throw new Error(`variant arm ${index} is out of range (${wire.fields.length} on the wire)`);
        }
        const [wireHash, wireRef] = wire.fields[index];
        const arm = this.fields.find(([, hash]) => hash === wireHash);
        if (!arm) {
            throw new Error(`the wire chose variant arm with hash ${wireHash}, unknown to ${this.name}`);
        }
        return { [arm[0]]: arm[2].decodeValue(r, deref(wireRef), deref) };
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Message encoding and decoding
// ─────────────────────────────────────────────────────────────────────────────

function encode(types: CandidType<any>[], values: unknown[]): Uint8Array {
    if (types.length !== values.length) {
        throw new Error(`Candid encode: ${types.length} type(s) but ${values.length} value(s)`);
    }
    const table = new TypeTable();
    for (const type of types) type.build(table);

    const out: number[] = [...MAGIC];
    table.encode(out);
    leb128(types.length, out);
    for (const type of types) sleb128(type.ref(table), out);
    for (let i = 0; i < types.length; i++) types[i].encodeValue(values[i], out);
    return Uint8Array.from(out);
}

function decode(types: CandidType<any>[], bytes: Uint8Array): unknown[] {
    const r = new Reader(bytes);
    for (const expected of MAGIC) {
        if (r.byte() !== expected) throw new Error('not a Candid message: bad "DIDL" magic');
    }

    const tableSize = r.count();
    const table: WireType[] = [];
    for (let i = 0; i < tableSize; i++) table.push(parseTableEntry(r));

    const deref: Deref = (ref) => {
        if (ref < 0) return { k: 'prim', code: ref };
        if (ref >= table.length) throw new Error(`type reference ${ref} is outside the table`);
        return table[ref];
    };

    const arity = r.count();
    const refs: number[] = [];
    for (let i = 0; i < arity; i++) refs.push(Number(r.sleb()));

    if (arity !== types.length) {
        throw new Error(`Candid decode: the message carries ${arity} value(s), expected ${types.length}`);
    }

    const values: unknown[] = [];
    for (let i = 0; i < types.length; i++) {
        values.push(types[i].decodeValue(r, deref(refs[i]), deref));
    }
    if (!r.exhausted) throw new Error('trailing bytes after the last Candid value');
    return values;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public surface
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The Candid type constructors and the two message functions.
 *
 * `Vec`, `Record` and `Variant` are memoised on their structural name so that
 * `IDL.Vec(IDL.Nat8)` written twice is one type, not two — the same identity
 * the type table's deduplication assumes.
 */
export const IDL = {
    Text: new TextType(),
    Nat8: new Nat8Type(),
    Nat64: new Nat64Type(),
    Null: new NullType(),

    Vec<T>(elem: CandidType<T>): CandidType<T[] | Uint8Array> {
        return new VecType(elem);
    },

    Record(fields: Record<string, CandidType<any>>): CandidType<Record<string, any>> {
        return new RecordType(fields);
    },

    Variant(fields: Record<string, CandidType<any>>): CandidType<Record<string, any>> {
        return new VariantType(fields);
    },

    encode,
    decode,
} as const;
